DROP TABLE BOOKS IF EXISTS;
DROP TABLE AUTHORS IF EXISTS;

CREATE TABLE AUTHORS (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE BOOKS (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    price INT NOT NULL,
    year_book INT,
    cover VARCHAR(255)
);